apiVersion: v1
kind: Pod
metadata:
  name: pod-with-block-volume
spec:
  containers:
    - name: blk-container
      image: nginx:latest
      volumeMounts:
        - name: data
          mountPath: /dev/xvda
  volumes:
  - name: data
    hostPath:
      # directory location on host
      # path: /dev/disk/by-path/ip-207.148.121.48:3260-iscsi-iqn.2017-10.io.opensds:97f85842-83af-4bf7-9167-91486cc09fb2-lun-1 
      path: /dev/sda
      # this field is optional
      type: BlockDevice
