dist: trusty
sudo: false

language: go
go_import_path: github.com/opensds/nbp

go:
  - 1.9.x
  - tip

env:
  matrix:
   - TARGET=amd64
   - TARGET=arm64
   - TARGET=arm
   - TARGET=386
   - TARGET=ppc64le

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
  exclude:
  - go: tip
    env: TARGET=arm
  - go: tip
    env: TARGET=arm64
  - go: tip
    env: TARGET=386
  - go: tip
    env: TARGET=ppc64le

install:
  - make

script:
  - go test -v github.com/opensds/nbp/csi/... -cover
  - go test -v github.com/opensds/nbp/flexvolume/... -cover

