apiVersion: v1
kind: Pod
metadata:
  name: nginx-lvm
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    volumeMounts:
    - name: "ee1918c2-aaa3-44d6-9c0e-65aedb712327"
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: "ee1918c2-aaa3-44d6-9c0e-65aedb712327"
    flexVolume:
      driver: "opensds.io/opensds"
      fsType: "ext4"

