kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: run-opensds-provisioner
subjects:
  - kind: ServiceAccount
    name: opensds-provisioner
    namespace: default
roleRef:
  kind: ClusterRole
  name: opensds-provisioner-runner
  apiGroup: rbac.authorization.k8s.io
