kind: Pod
apiVersion: v1
metadata:
  name: opensds-provisioner
spec:
  serviceAccount: opensds-provisioner
  containers:
    - name: opensds-provisioner
      image: opensdsio/opensds-provisioner:latest
      securityContext:
      args:
        - "-endpoint=http://192.168.56.100:50040"
      imagePullPolicy: "IfNotPresent"
