apiVersion: v1
kind: ServiceAccount
metadata:
  name: opensds-provisioner

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: opensds-provisioner-runner
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["get"]
  - apiGroups: ["extensions"]
    resources: ["podsecuritypolicies"]
    resourceNames: ["opensds-provisioner"]
    verbs: ["use"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: run-opensds-provisioner
subjects:
  - kind: ServiceAccount
    name: opensds-provisioner
    namespace: default
roleRef:
  kind: ClusterRole
  name: opensds-provisioner-runner
  apiGroup: rbac.authorization.k8s.io

---
kind: Pod
apiVersion: v1
metadata:
  name: opensds-provisioner
spec:
  serviceAccount: opensds-provisioner
  containers:
    - name: opensds-provisioner
      image: opensdsio/opensds-provisioner:latest
      securityContext:
      args:
        - "-endpoint=$(OPENSDS_ENDPOINT)"
        - "-authstrategy=$(OPENSDS_AUTH_STRATEGY)"
      env:
        - name: OPENSDS_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: opensds-provisioner-configmap
              key: opensdsendpoint
        - name: OPENSDS_AUTH_STRATEGY
          valueFrom:
            configMapKeyRef:
              name: opensds-provisioner-configmap
              key: opensdsauthstrategy
        - name: OS_AUTH_URL
          valueFrom:
            configMapKeyRef:
              name: opensds-provisioner-configmap
              key: osauthurl
        - name: OS_USERNAME
          valueFrom:
            configMapKeyRef:
              name: opensds-provisioner-configmap
              key: osusername
        - name: OS_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: opensds-provisioner-configmap
              key: ospassword
        - name: OS_TENANT_NAME
          valueFrom:
            configMapKeyRef:
              name: opensds-provisioner-configmap
              key: ostenantname
        - name: OS_PROJECT_NAME
          valueFrom:
            configMapKeyRef:
              name: opensds-provisioner-configmap
              key: osprojectname
        - name: OS_USER_DOMAIN_ID
          valueFrom:
            configMapKeyRef:
              name: opensds-provisioner-configmap
              key: osuserdomainid
      imagePullPolicy: "IfNotPresent"
