# This YAML file contains nginx & csi opensds driver objects,
# which are necessary to run nginx with csi opensds driver.

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-opensdsplugin
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  dataSource:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: new-snapshot-demo
  storageClassName: csi-sc-opensdsplugin

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx 
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    volumeMounts:
      - mountPath: /var/lib/www/html
        name: csi-data-opensdsplugin 
  volumes:
  - name: csi-data-opensdsplugin
    persistentVolumeClaim:
      claimName: csi-pvc-opensdsplugin
      readOnly: false
